name: flutter_input_tracker
description: A Flutter plugin for global keyboard and mouse tracking.
version: 0.0.2
homepage: https://github.com/Dishant-22
repository: https://github.com/Dishant-22/flutter_input_tracker
issue_tracker: https://github.com/Dishant-22/flutter_input_tracker/issues

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterInputTrackerPluginCApi